version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=microbit
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - '3306:3306'
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      iothub:
        ipv4_address: "192.168.80.2"
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    user: "1000"
    environment:
    - GF_DATABASE_TYPE=mysql
    - GF_DATABASE_HOST=db
    - GF_DATABASE_PORT=3306
    - GF_DATABASE_NAME=microbit
    - GF_DATABASE_USER=root
    - GF_DATABASE_PASSWORD=admin
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/data:/var/lib/grafana
    networks:
      iothub: 
        ipv4_address: "192.168.80.3"
volumes:
  db:
    driver: local
networks:
  iothub:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.80.0/24"